// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: paxos.proto

package paxos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosService_Prepare_FullMethodName            = "/paxos.PaxosService/Prepare"
	PaxosService_Accept_FullMethodName             = "/paxos.PaxosService/Accept"
	PaxosService_Commit_FullMethodName             = "/paxos.PaxosService/Commit"
	PaxosService_ProcessTransaction_FullMethodName = "/paxos.PaxosService/ProcessTransaction"
	PaxosService_PrintBalance_FullMethodName       = "/paxos.PaxosService/PrintBalance"
	PaxosService_PrintLog_FullMethodName           = "/paxos.PaxosService/PrintLog"
	PaxosService_PrintDB_FullMethodName            = "/paxos.PaxosService/PrintDB"
	PaxosService_Performance_FullMethodName        = "/paxos.PaxosService/Performance"
	PaxosService_Sync_FullMethodName               = "/paxos.PaxosService/Sync"
	PaxosService_UpdateLiveServers_FullMethodName  = "/paxos.PaxosService/UpdateLiveServers"
)

// PaxosServiceClient is the client API for PaxosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service
type PaxosServiceClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseResponse, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	ProcessTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error)
	PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error)
	PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error)
	Performance(ctx context.Context, in *PerformanceRequest, opts ...grpc.CallOption) (*PerformanceResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	UpdateLiveServers(ctx context.Context, in *UpdateLiveServersRequest, opts ...grpc.CallOption) (*UpdateLiveServersResponse, error)
}

type paxosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosServiceClient(cc grpc.ClientConnInterface) PaxosServiceClient {
	return &paxosServiceClient{cc}
}

func (c *paxosServiceClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseResponse)
	err := c.cc.Invoke(ctx, PaxosService_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptedResponse)
	err := c.cc.Invoke(ctx, PaxosService_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, PaxosService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) ProcessTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, PaxosService_ProcessTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintBalanceResponse)
	err := c.cc.Invoke(ctx, PaxosService_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintLogResponse)
	err := c.cc.Invoke(ctx, PaxosService_PrintLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintDBResponse)
	err := c.cc.Invoke(ctx, PaxosService_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Performance(ctx context.Context, in *PerformanceRequest, opts ...grpc.CallOption) (*PerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceResponse)
	err := c.cc.Invoke(ctx, PaxosService_Performance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, PaxosService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosServiceClient) UpdateLiveServers(ctx context.Context, in *UpdateLiveServersRequest, opts ...grpc.CallOption) (*UpdateLiveServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLiveServersResponse)
	err := c.cc.Invoke(ctx, PaxosService_UpdateLiveServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosServiceServer is the server API for PaxosService service.
// All implementations must embed UnimplementedPaxosServiceServer
// for forward compatibility.
//
// Define the service
type PaxosServiceServer interface {
	Prepare(context.Context, *PrepareRequest) (*PromiseResponse, error)
	Accept(context.Context, *AcceptRequest) (*AcceptedResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	ProcessTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error)
	PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error)
	PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error)
	Performance(context.Context, *PerformanceRequest) (*PerformanceResponse, error)
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	UpdateLiveServers(context.Context, *UpdateLiveServersRequest) (*UpdateLiveServersResponse, error)
	mustEmbedUnimplementedPaxosServiceServer()
}

// UnimplementedPaxosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosServiceServer struct{}

func (UnimplementedPaxosServiceServer) Prepare(context.Context, *PrepareRequest) (*PromiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosServiceServer) Accept(context.Context, *AcceptRequest) (*AcceptedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosServiceServer) ProcessTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransaction not implemented")
}
func (UnimplementedPaxosServiceServer) PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedPaxosServiceServer) PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedPaxosServiceServer) PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPaxosServiceServer) Performance(context.Context, *PerformanceRequest) (*PerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Performance not implemented")
}
func (UnimplementedPaxosServiceServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedPaxosServiceServer) UpdateLiveServers(context.Context, *UpdateLiveServersRequest) (*UpdateLiveServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLiveServers not implemented")
}
func (UnimplementedPaxosServiceServer) mustEmbedUnimplementedPaxosServiceServer() {}
func (UnimplementedPaxosServiceServer) testEmbeddedByValue()                      {}

// UnsafePaxosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosServiceServer will
// result in compilation errors.
type UnsafePaxosServiceServer interface {
	mustEmbedUnimplementedPaxosServiceServer()
}

func RegisterPaxosServiceServer(s grpc.ServiceRegistrar, srv PaxosServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaxosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosService_ServiceDesc, srv)
}

func _PaxosService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_ProcessTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).ProcessTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintBalance(ctx, req.(*PrintBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintLog(ctx, req.(*PrintLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).PrintDB(ctx, req.(*PrintDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Performance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Performance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Performance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Performance(ctx, req.(*PerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosService_UpdateLiveServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLiveServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosServiceServer).UpdateLiveServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosService_UpdateLiveServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosServiceServer).UpdateLiveServers(ctx, req.(*UpdateLiveServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosService_ServiceDesc is the grpc.ServiceDesc for PaxosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosService",
	HandlerType: (*PaxosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _PaxosService_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosService_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PaxosService_Commit_Handler,
		},
		{
			MethodName: "ProcessTransaction",
			Handler:    _PaxosService_ProcessTransaction_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _PaxosService_PrintBalance_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _PaxosService_PrintLog_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _PaxosService_PrintDB_Handler,
		},
		{
			MethodName: "Performance",
			Handler:    _PaxosService_Performance_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _PaxosService_Sync_Handler,
		},
		{
			MethodName: "UpdateLiveServers",
			Handler:    _PaxosService_UpdateLiveServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
